import { AnnouncementSettings, GameState, Team } from '../types';

export const DEMO_TEAMS: Record<string, Team> = {
  'spartans': {
    id: 'spartans',
    schoolName: 'South Paulding',
    mascot: 'Spartans',
    shortName: 'Spartans',
    abbreviation: 'SP',
    jerseyColor: '#1e3a8a', // Navy blue
    jerseyTextColor: '#ffffff',
    defaultQuarterbackPlayerId: 'sp-12',
    roster: [
      { id: 'sp-12', jerseyNumber: '12', firstName: 'Nathan', lastName: 'Smith', displayName: 'Nathan Smith', phoneticPronunciation: 'NAY-thun Smith', position: 'QB', unit: 'offense', active: true },
      { id: 'sp-33', jerseyNumber: '33', firstName: 'Nathan', lastName: 'Bryant', displayName: 'Nathan Bryant', phoneticPronunciation: 'NAY-thun BRY-ant', position: 'RB', unit: 'offense', active: true },
      { id: 'sp-44', jerseyNumber: '44', firstName: 'John', lastName: 'Davis', displayName: 'John Davis', phoneticPronunciation: 'John DAY-vis', position: 'LB', unit: 'defense', active: true },
      { id: 'sp-52', jerseyNumber: '52', firstName: 'David', lastName: 'Williams', displayName: 'David Williams', phoneticPronunciation: 'DAY-vid WILL-yums', position: 'LB', unit: 'defense', active: true },
      { id: 'sp-88', jerseyNumber: '88', firstName: 'Tyler', lastName: 'Jones', displayName: 'Tyler Jones', phoneticPronunciation: 'TY-ler Jones', position: 'WR', unit: 'offense', active: true },
      { id: 'sp-15', jerseyNumber: '15', firstName: 'Player', lastName: '15', displayName: 'Player 15', position: 'UNK', unit: 'offense', active: true },
      { id: 'sp-16', jerseyNumber: '16', firstName: 'Player', lastName: '16', displayName: 'Player 16', position: 'UNK', unit: 'offense', active: true },
      { id: 'sp-17', jerseyNumber: '17', firstName: 'Player', lastName: '17', displayName: 'Player 17', position: 'UNK', unit: 'offense', active: true },
      { id: 'sp-18', jerseyNumber: '18', firstName: 'Player', lastName: '18', displayName: 'Player 18', position: 'UNK', unit: 'offense', active: true },
      { id: 'sp-19', jerseyNumber: '19', firstName: 'Player', lastName: '19', displayName: 'Player 19', position: 'UNK', unit: 'offense', active: true },
      { id: 'sp-20', jerseyNumber: '20', firstName: 'Player', lastName: '20', displayName: 'Player 20', position: 'UNK', unit: 'offense', active: true },
      { id: 'sp-21', jerseyNumber: '21', firstName: 'Player', lastName: '21', displayName: 'Player 21', position: 'UNK', unit: 'offense', active: true },
      { id: 'sp-22', jerseyNumber: '22', firstName: 'Player', lastName: '22', displayName: 'Player 22', position: 'UNK', unit: 'offense', active: true },
      { id: 'sp-23', jerseyNumber: '23', firstName: 'Player', lastName: '23', displayName: 'Player 23', position: 'UNK', unit: 'offense', active: true },
      { id: 'sp-24', jerseyNumber: '24', firstName: 'Player', lastName: '24', displayName: 'Player 24', position: 'UNK', unit: 'offense', active: true },
      { id: 'sp-25', jerseyNumber: '25', firstName: 'Player', lastName: '25', displayName: 'Player 25', position: 'UNK', unit: 'offense', active: true },
      { id: 'sp-26', jerseyNumber: '26', firstName: 'Player', lastName: '26', displayName: 'Player 26', position: 'UNK', unit: 'offense', active: true },
      { id: 'sp-27', jerseyNumber: '27', firstName: 'Player', lastName: '27', displayName: 'Player 27', position: 'UNK', unit: 'offense', active: true },
      { id: 'sp-28', jerseyNumber: '28', firstName: 'Player', lastName: '28', displayName: 'Player 28', position: 'UNK', unit: 'offense', active: true },
      { id: 'sp-29', jerseyNumber: '29', firstName: 'Player', lastName: '29', displayName: 'Player 29', position: 'UNK', unit: 'offense', active: true },
      { id: 'sp-30', jerseyNumber: '30', firstName: 'Player', lastName: '30', displayName: 'Player 30', position: 'UNK', unit: 'offense', active: true },
      { id: 'sp-31', jerseyNumber: '31', firstName: 'Player', lastName: '31', displayName: 'Player 31', position: 'UNK', unit: 'offense', active: true },
      { id: 'sp-32', jerseyNumber: '32', firstName: 'Player', lastName: '32', displayName: 'Player 32', position: 'UNK', unit: 'offense', active: true },
      { id: 'sp-33', jerseyNumber: '33', firstName: 'Player', lastName: '33', displayName: 'Player 33', position: 'UNK', unit: 'offense', active: true },
      { id: 'sp-34', jerseyNumber: '34', firstName: 'Player', lastName: '34', displayName: 'Player 34', position: 'UNK', unit: 'offense', active: true },
      { id: 'sp-35', jerseyNumber: '35', firstName: 'Player', lastName: '35', displayName: 'Player 35', position: 'UNK', unit: 'offense', active: true },
      { id: 'sp-36', jerseyNumber: '36', firstName: 'Player', lastName: '36', displayName: 'Player 36', position: 'UNK', unit: 'offense', active: true },
      { id: 'sp-37', jerseyNumber: '37', firstName: 'Player', lastName: '37', displayName: 'Player 37', position: 'UNK', unit: 'offense', active: true },
      { id: 'sp-38', jerseyNumber: '38', firstName: 'Player', lastName: '38', displayName: 'Player 38', position: 'UNK', unit: 'offense', active: true },
      { id: 'sp-39', jerseyNumber: '39', firstName: 'Player', lastName: '39', displayName: 'Player 39', position: 'UNK', unit: 'offense', active: true },

    ],
  },
  'hornets': {
    id: 'hornets',
    schoolName: 'Hiram',
    mascot: 'Hornets',
    shortName: 'Hornets',
    abbreviation: 'HIR',
    jerseyColor: '#18181b', // Black / Gold accent
    jerseyTextColor: '#facc15',
    defaultQuarterbackPlayerId: 'hh-7',
    roster: [
      { id: 'hh-2', jerseyNumber: '2', firstName: 'Jordan', lastName: 'Hill', displayName: 'Jordan Hill', phoneticPronunciation: 'JOR-dun Hill', position: 'DB', unit: 'defense', active: true },
      { id: 'hh-7', jerseyNumber: '7', firstName: 'Marcus', lastName: 'Green', displayName: 'Marcus Green', phoneticPronunciation: 'MAR-kus Green', position: 'QB', unit: 'offense', active: true },
      { id: 'hh-24', jerseyNumber: '24', firstName: 'Michael', lastName: 'Brown', displayName: 'Michael Brown', phoneticPronunciation: 'MY-kul Brown', position: 'DB', unit: 'defense', active: true },
      { id: 'hh-44', jerseyNumber: '44', firstName: 'Michael', lastName: 'Johnson', displayName: 'Michael Johnson', phoneticPronunciation: 'MY-kul JON-sun', position: 'LB', unit: 'defense', active: true },
      { id: 'hh-81', jerseyNumber: '81', firstName: 'Chris', lastName: 'Taylor', displayName: 'Chris Taylor', phoneticPronunciation: 'Chris TAY-lor', position: 'WR', unit: 'offense', active: true },
      { id: 'hh-15', jerseyNumber: '15', firstName: 'Player', lastName: '15', displayName: 'Player 15', position: 'UNK', unit: 'offense', active: true },
      { id: 'hh-16', jerseyNumber: '16', firstName: 'Player', lastName: '16', displayName: 'Player 16', position: 'UNK', unit: 'offense', active: true },
      { id: 'hh-17', jerseyNumber: '17', firstName: 'Player', lastName: '17', displayName: 'Player 17', position: 'UNK', unit: 'offense', active: true },
      { id: 'hh-18', jerseyNumber: '18', firstName: 'Player', lastName: '18', displayName: 'Player 18', position: 'UNK', unit: 'offense', active: true },
      { id: 'hh-19', jerseyNumber: '19', firstName: 'Player', lastName: '19', displayName: 'Player 19', position: 'UNK', unit: 'offense', active: true },
      { id: 'hh-20', jerseyNumber: '20', firstName: 'Player', lastName: '20', displayName: 'Player 20', position: 'UNK', unit: 'offense', active: true },
      { id: 'hh-21', jerseyNumber: '21', firstName: 'Player', lastName: '21', displayName: 'Player 21', position: 'UNK', unit: 'offense', active: true },
      { id: 'hh-22', jerseyNumber: '22', firstName: 'Player', lastName: '22', displayName: 'Player 22', position: 'UNK', unit: 'offense', active: true },
      { id: 'hh-23', jerseyNumber: '23', firstName: 'Player', lastName: '23', displayName: 'Player 23', position: 'UNK', unit: 'offense', active: true },
      { id: 'hh-24', jerseyNumber: '24', firstName: 'Player', lastName: '24', displayName: 'Player 24', position: 'UNK', unit: 'offense', active: true },
      { id: 'hh-25', jerseyNumber: '25', firstName: 'Player', lastName: '25', displayName: 'Player 25', position: 'UNK', unit: 'offense', active: true },
      { id: 'hh-26', jerseyNumber: '26', firstName: 'Player', lastName: '26', displayName: 'Player 26', position: 'UNK', unit: 'offense', active: true },
      { id: 'hh-27', jerseyNumber: '27', firstName: 'Player', lastName: '27', displayName: 'Player 27', position: 'UNK', unit: 'offense', active: true },
      { id: 'hh-28', jerseyNumber: '28', firstName: 'Player', lastName: '28', displayName: 'Player 28', position: 'UNK', unit: 'offense', active: true },
      { id: 'hh-29', jerseyNumber: '29', firstName: 'Player', lastName: '29', displayName: 'Player 29', position: 'UNK', unit: 'offense', active: true },
      { id: 'hh-30', jerseyNumber: '30', firstName: 'Player', lastName: '30', displayName: 'Player 30', position: 'UNK', unit: 'offense', active: true },
      { id: 'hh-31', jerseyNumber: '31', firstName: 'Player', lastName: '31', displayName: 'Player 31', position: 'UNK', unit: 'offense', active: true },
      { id: 'hh-32', jerseyNumber: '32', firstName: 'Player', lastName: '32', displayName: 'Player 32', position: 'UNK', unit: 'offense', active: true },
      { id: 'hh-33', jerseyNumber: '33', firstName: 'Player', lastName: '33', displayName: 'Player 33', position: 'UNK', unit: 'offense', active: true },
      { id: 'hh-34', jerseyNumber: '34', firstName: 'Player', lastName: '34', displayName: 'Player 34', position: 'UNK', unit: 'offense', active: true },
      { id: 'hh-35', jerseyNumber: '35', firstName: 'Player', lastName: '35', displayName: 'Player 35', position: 'UNK', unit: 'offense', active: true },
      { id: 'hh-36', jerseyNumber: '36', firstName: 'Player', lastName: '36', displayName: 'Player 36', position: 'UNK', unit: 'offense', active: true },
      { id: 'hh-37', jerseyNumber: '37', firstName: 'Player', lastName: '37', displayName: 'Player 37', position: 'UNK', unit: 'offense', active: true },
      { id: 'hh-38', jerseyNumber: '38', firstName: 'Player', lastName: '38', displayName: 'Player 38', position: 'UNK', unit: 'offense', active: true },
      { id: 'hh-39', jerseyNumber: '39', firstName: 'Player', lastName: '39', displayName: 'Player 39', position: 'UNK', unit: 'offense', active: true },

    ],
  },
  'eagles': {
    id: 'eagles',
    schoolName: 'Eastside',
    mascot: 'Eagles',
    shortName: 'Eagles',
    abbreviation: 'EAG',
    jerseyColor: '#047857', // Emerald green
    jerseyTextColor: '#ffffff',
    defaultQuarterbackPlayerId: 'eag-2',
    roster: [
      { id: 'eag-2', jerseyNumber: '2', firstName: 'Ethan', lastName: 'Carter', displayName: 'Ethan Carter', phoneticPronunciation: 'EE-thun KAR-ter', position: 'QB', unit: 'offense', active: true },
      { id: 'eag-3', jerseyNumber: '3', firstName: 'Mason', lastName: 'Brooks', displayName: 'Mason Brooks', phoneticPronunciation: 'MAY-sun BROOKS', position: 'RB', unit: 'offense', active: true },
      { id: 'eag-11', jerseyNumber: '11', firstName: 'Noah', lastName: 'Bennett', displayName: 'Noah Bennett', phoneticPronunciation: 'NOH-uh BEN-it', position: 'WR', unit: 'offense', active: true },
      { id: 'eag-17', jerseyNumber: '17', firstName: 'Luke', lastName: 'Simmons', displayName: 'Luke Simmons', phoneticPronunciation: 'LOOK SIM-unz', position: 'LB', unit: 'defense', active: true },
    ],
  },
  'lions': {
    id: 'lions',
    schoolName: 'Lakeside',
    mascot: 'Lions',
    shortName: 'Lions',
    abbreviation: 'LIO',
    jerseyColor: '#b91c1c', // Deep Red
    jerseyTextColor: '#ffffff',
    defaultQuarterbackPlayerId: 'lio-1',
    roster: [
      { id: 'lio-1', jerseyNumber: '1', firstName: 'Alexander', lastName: 'Vance', displayName: 'Alexander Vance', phoneticPronunciation: 'AL-ex VANCE', position: 'QB', unit: 'offense', active: true },
      { id: 'lio-10', jerseyNumber: '10', firstName: 'Daniel', lastName: 'Cross', displayName: 'Daniel Cross', phoneticPronunciation: 'DAN-yul CROSS', position: 'RB', unit: 'offense', active: true },
      { id: 'lio-22', jerseyNumber: '22', firstName: 'Xavier', lastName: 'Knight', displayName: 'Xavier Knight', phoneticPronunciation: 'ZAY-vee-er NITE', position: 'DB', unit: 'defense', active: true },
    ],
  },
};

export const INITIAL_ANNOUNCEMENT_SETTINGS: AnnouncementSettings = {
  includePlayerNames: true,
  includeTacklers: true,
  sayJerseyPrefix: true,
  useOrdinalDowns: true,
  useMascotName: true,
  showPhoneticHints: true,
  autoTTS: false,
};

export function createInitialGameState(homeId = 'spartans', awayId = 'hornets'): GameState {
  return {
    homeTeamId: homeId,
    awayTeamId: awayId,
    leftFieldTeamId: homeId,
    rightFieldTeamId: awayId,
    possessionTeamId: homeId,
    quarter: 1,
    clock: '12:00',
    homeScore: 0,
    awayScore: 0,
    down: 1,
    distance: 10,
    ballPosition: {
      territoryTeamId: homeId,
      yardLine: 35,
      isMidfield: false,
    },
    lineToGain: {
      territoryTeamId: homeId,
      yardLine: 45,
      isMidfield: false,
    },
    status: 'live',
  };
}
